services:
  - type: web
    name: shoppinglyx
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn shoppinglyx.wsgi"
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: False
